// Car catalog, parts, paints and upgrade tables
// Voxel legend (car faces right, light from top-left):
//  K outline | h paint highlight, B paint, b paint shadow, d paint deep shadow | S accent, s accent shadow
//  G glass, g glass shadow, w glass glint | L headlight, R taillight, O indicator | T trim dark, t trim mid
//  C chrome, c chrome shadow | V vent/intake | I interior | any other char -> car.fixed palette
(function () {
  const BODY_ROWS = (a) => a; // readability helper

  const STARTERS = [
    {
      id: 'st_vice', gang: 0, name: 'OCEAN CHEETAH', year: 1986, era: 'СТАРТ', price: 4200, desc: 'БАНДИТСЬКИЙ КЛИН ОУШЕН-ДРАЙВ',
      stats: { top: 138, accel: 280, armor: 95, mass: 0.7, restComp: 2.4, damp: 0.45, hill: 0.55, launch: 1.3, air: 1 },
      paint: '#f2eefa', accent: '#ff3ea5', rims: 'chrome', wheelX: [-10, 9], wheelY: 4,
      rows: BODY_ROWS([
        '..........KKKKKKKK..............',
        '........KKhhhhhhhKgK............',
        '......KKhBBBBBBBBKgGGK..........',
        '....KKhBBBBBBBBBBKggGGGK........',
        '..KKhhhhhhhhhhhhhhKKKKKKKKKK....',
        '.KRBBBBBBBBBBBBBBBBBBBBBBBBBBKK.',
        '.KRSSSSSSSSSSSSSSSSSSSSSSSSSSSLK',
        '.KBBBBBBBBBBBBBBBBBBBBBBBBBBBBBK',
        '.KbddddbbbbbbbbbbbbbbbbbdddbbbbK',
        '.KdddddddddddddddddddddddddddddK',
        '..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..',
      ]),
    },
    {
      id: 'st_kings', gang: 1, name: 'KENTE DEVILLE', year: 1983, era: 'СТАРТ', price: 3800, desc: 'ЛОУРАЙДЕР НА ГІДРАВЛІЦІ',
      stats: { top: 120, accel: 200, armor: 150, mass: 1.1, restComp: 3.2, damp: 0.22, hill: 0.55, launch: 1.3, air: 1 },
      paint: '#7b2fbe', accent: '#ffc31f', rims: 'gold', wheelX: [-11, 11], wheelY: 5,
      fixed: { r: '#e0302a', y: '#ffd23f', n: '#2fa84f' },
      rows: BODY_ROWS([
        '...........KKKKKKKKKKKK...........',
        '..........KhhhhhhhhhhhhK..........',
        '.........KgGGGKhKgGGGGGgKK........',
        '........KgGGGGKhKgGGGGGGggK.......',
        '..KKKKKKhhhhhhhhhhhhhhhhhhhKKKKK..',
        '.KRhhhhhhhhhhhhhhhhhhhhhhhhhhhhhLK',
        '.KSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSK',
        '.KrynKrynKrynKrynKrynKrynKrynKrynK',
        '.KBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.',
      ]),
    },
    {
      id: 'st_havana', gang: 2, name: 'HAVANA BEL-AIR', year: 1957, era: 'СТАРТ', price: 4000, desc: 'КУБИНСЬКА КЛАСИКА 50-Х',
      stats: { top: 128, accel: 240, armor: 120, mass: 0.9, restComp: 2.8, damp: 0.35, hill: 0.55, launch: 1.3, air: 1 },
      paint: '#29c7b8', accent: '#fff1c9', rims: 'white', wheelX: [-10, 9], wheelY: 5,
      fixed: { F: '#ff6a1f', f: '#ffd23f' },
      rows: BODY_ROWS([
        '.........KKKKKKKKKKK............',
        '........KSSSSSSSSSSSK...........',
        '.......KgGGKSSKgGGGGGK..........',
        '......KgGGGKSSKgGGGGGGK.........',
        '.KK..KBBBBBBBBBBBBBBBBBKKKK.....',
        '.KBKKhhhhhhhhhhhhhhhhhhhhhhhKKK.',
        '.KRBBBBBBBBBBBBBBBBBBBBBBfFFFBLK',
        '.KBBBBBBBBBBBBBBBBBBBBfFFFfFFBBK',
        '.KCSSSSSSSSSSSSSSSSSSSSSSSSSSSCK',
        '.KCsssssssssssssssssssssssssssCK',
        '..KKKKKKKKKKKKKKKKKKKKKKKKKKKKK.',
      ]),
    },
  ];

  // stats: top speed px/s, accel, armor, mass; hill = climb assist, launch = ramp boost, air = air gravity mult
  const SHOP = [
    {
      id: 'delta81', name: 'DELTA DMX', year: 1981, era: 80, price: 4500, paint: '#b9bfcc', accent: '#24202e', rims: 'chrome',
      stats: { top: 128, accel: 230, armor: 130, mass: 1.0, restComp: 2.6, damp: 0.4, hill: 0.55, launch: 1.3, air: 1.0 },
      desc: 'НЕРЖАВІЙКА З МАЙБУТНЬОГО', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '...........KKKKKKKKK..............',
        '..........KhhhhhhhhhK.............',
        '........KTtgGGGGGGGwgK............',
        '......KTtTtgGGGGGGGGGgK...........',
        '.KKKKKhhhhhhhhhhhhhhhhhKKKKKKKKKK.',
        '.KRhhhBBBBBBBBBBBBBBBbhhhhhhhhhhLK',
        '.KRBBBBBBBBBBBBBBBBBBbBBBBBBBBBOLK',
        '.KbBBBBBBBBBBBBBBBBBBbBBBBBBBBBBBK',
        '.KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK',
        '.KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK',
        '..KVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK.',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'contessa85', name: 'BULLO CONTESSA', year: 1985, era: 80, price: 9000, paint: '#f5c131', accent: '#24202e', rims: 'black',
      stats: { top: 146, accel: 300, armor: 95, mass: 0.8, restComp: 2.3, damp: 0.45, hill: 0.55, launch: 1.32, air: 0.98 },
      desc: 'КЛИН, ЩО ЗЛАМАВ 80-ТІ', wheelX: [-10, 10], wheelY: 3.5,
      rows: [
        '..................................',
        '............KKKKKKKK..............',
        '..........KhhhhhhhhhhK............',
        '......KKhhgGGGGGGGGGwgK...........',
        '..KKKKhBBBgGGGGGGGGGGwgKKKK.......',
        '.KRBBBBBBBBBbVVVbBBBBBBhhhhhhKKKK.',
        '.KRBBBBBBBBBBVVVBBBBBBBBBBBBBhhLKK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK.',
        '.KdddddddddddddddddddddddddddddK..',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTK...',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKK.....',
        '..................................',
      ],
    },
    {
      id: 'rosso86', name: 'ROSSO TR', year: 1986, era: 80, price: 8000, paint: '#f2eefa', accent: '#24202e', rims: 'chrome',
      stats: { top: 144, accel: 280, armor: 105, mass: 0.85, restComp: 2.4, damp: 0.42, hill: 0.56, launch: 1.3, air: 1.0 },
      desc: 'БІЛИЙ КОРОЛЬ ОУШЕН-ДРАЙВ', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '..................................',
        '............KKKKKKK...............',
        '..........KhhhhhhhhK..............',
        '........KKhgGGGGGGwgK.............',
        '..KKKKKKhhBgGGGGGGGGwgKKKKKKKKK...',
        '.KhhhhhhhhhBBBBBBBBBBBBhhhhhhhhhK.',
        '.KRBBBBBBBBBVVVVVVVVVVVBBBBBBBBOK.',
        '.KRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBK.',
        '.KbbbbbbbbbbVVVVVVVVVVVbbbbbbbbbbK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '..KddddddddddddddddddddddddddddK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'porza87', name: 'PORZA 930 TURBO', year: 1987, era: 80, price: 7000, paint: '#24202e', accent: '#d8203a', rims: 'chrome',
      stats: { top: 140, accel: 310, armor: 100, mass: 0.75, restComp: 2.4, damp: 0.42, hill: 0.58, launch: 1.3, air: 0.98 },
      desc: 'ТУРБО-ЯМА І КИТОВИЙ ХВІСТ', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '.............KKKKK................',
        '...........KKhhhhhKK..............',
        '.........KKhgGGGGGwgK.............',
        '.......KKhhgGGGGGGGwgK............',
        '.....KKhhhhBgGGGGGGGwgKKKKKKKK....',
        '...KhhhBBBBBBBBBBBBBBBBhhhhhhLhK..',
        '..KRBBBBBBBBBBBBBBBBBBBBBBBBBBBBK.',
        '.KRBBBBBBBBBBBBBbBBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '.KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK',
        '..KddddddddddddddddddddddddddddK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKK....',
      ],
    },
    {
      id: 'bav88', name: 'BAVARIA E30 SPORT', year: 1988, era: 80, price: 7500, paint: '#3b3fb8', accent: '#d8203a', rims: 'white',
      stats: { top: 134, accel: 290, armor: 115, mass: 0.75, restComp: 2.5, damp: 0.4, hill: 0.64, launch: 1.3, air: 1.0 },
      desc: 'КУБИК, ЩО ВИГРАЄ ТРЕКИ', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '..........KKKKKKKKKKK.............',
        '.........KhhhhhhhhhhhK............',
        '........KgGGGGwTgGGGGGwK..........',
        '.......KgGGGGGwTgGGGGGGwK.........',
        '.KKKKKKhhhhhhhhhhhhhhhhhhKKKKKKKK.',
        '.KhhhhhBBBBBBBBBBBBBBBBBBhhhhhhhCK',
        '.KRRBBBBBBBBBBBBBBBBBBBBBBBBBBBLVK',
        '.KSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSK.',
        '.KBBBBBBBBBBBBBBbBBBBBBBBBBBBBBBBK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'furia89', name: 'FURIA F40', year: 1989, era: 80, price: 12500, paint: '#d8203a', accent: '#24202e', rims: 'chrome',
      stats: { top: 152, accel: 340, armor: 90, mass: 0.7, restComp: 2.2, damp: 0.46, hill: 0.58, launch: 1.34, air: 0.96 },
      desc: 'СИРИЙ ГОНОЧНИЙ ЗВІР', wheelX: [-10, 10], wheelY: 4, wing: [[0, 0, 7, 3], [0, 3, 6, 5]],
      rows: [
        '..................................',
        '.KKKKKK.........KKKKKK............',
        '.KhhhhK........KhhhhhhK...........',
        '..KKK...KTtTtTgGGGGGGwgK..........',
        '...K..KTtTtTtTgGGGGGGGGwgKKKKK....',
        '.KKKKhhhhhhhhhBBBBBBBBBBBBhhhhhhK.',
        '.KRBBBBBBBBBBBBVVVBBBBBBBBBBBBBLK.',
        '.KRBBBBBBBBBBBBBVVBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'hondo91', name: 'HONDO NSR', year: 1991, era: 90, price: 14000, paint: '#29e0b0', accent: '#24202e', rims: 'white',
      stats: { top: 150, accel: 320, armor: 110, mass: 0.75, restComp: 2.4, damp: 0.42, hill: 0.62, launch: 1.32, air: 0.96 },
      desc: 'ТОЧНІСТЬ ЯК У ШВЕЙЦАРСЬКОГО ГОДИННИКА', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '...........KKKKKKKK...............',
        '.........KKhhhhhhhhK..............',
        '........KgGGGGGGGGGwgK............',
        '.KKKKKKhgGGGGGGGGGGGwgK...........',
        '.KhhhhhhBBBBBBBBBBBBBBBKKKKKKKKK..',
        '.KRBBBBBBBBBBBBBBBBBBBBhhhhhhhhKK.',
        '.KRBBBBBBBBBBVVVBBBBBBBBBBBBBBBLK.',
        '.KBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'corsa90', name: 'CORSA C4 ZR', year: 1990, era: 90, price: 13000, paint: '#ff3ea5', accent: '#24202e', rims: 'chrome',
      stats: { top: 150, accel: 300, armor: 120, mass: 0.9, restComp: 2.6, damp: 0.38, hill: 0.56, launch: 1.3, air: 1.0 },
      desc: 'ДОВГИЙ КАПОТ, ЧИСТИЙ V8', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '..........KKKKKKK.................',
        '........KKhhhhhhhK................',
        '......KKgGGGGGGGGgK...............',
        '....KKgGGGGGGGGGGGwgK.............',
        '.KKKhhhhhhhhhhhhhhhhhhgKKKKKKKKKK.',
        '.KRhBBBBBBBBBBBBBBBBBBBhhhhhhhhhK.',
        '.KRBBBBBBBBBBBBBBBBBBBBBBBBBBBBLK.',
        '.KBBBBBBBBBBBBVVVVBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'vipra92', name: 'VIPRA RT', year: 1992, era: 90, price: 17000, paint: '#2f5bd8', accent: '#f2eefa', rims: 'chrome',
      stats: { top: 156, accel: 330, armor: 115, mass: 0.9, restComp: 2.6, damp: 0.38, hill: 0.57, launch: 1.3, air: 1.0 },
      desc: 'V10 І БОКОВІ ВИХЛОПИ', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '..................................',
        '..................................',
        '..........K.........K.............',
        '.........KtK.......KgK............',
        '.KKKKKKKKtKIIIIIIIKgGK............',
        '.KhhhhhhhhhhhhhhhhhhhhSShhhhhhKK..',
        '.KRBBSSBBBBBBBBBBBBBBBBBSSBBBBBBK.',
        '.KRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbOK',
        '.KbbbbbbbbbbCCCCCCCCbbbbbbbbbbbbbK',
        '..KdddddddddccccccccdddddddddddK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'diablo94', name: 'BULLO DIABOLO', year: 1994, era: 90, price: 22000, paint: '#8a3be8', accent: '#24202e', rims: 'black',
      stats: { top: 160, accel: 340, armor: 110, mass: 0.85, restComp: 2.3, damp: 0.44, hill: 0.56, launch: 1.34, air: 0.97 },
      desc: 'ДИЯВОЛ ІЗ ВЕЛИКИМ КРИЛОМ', wheelX: [-10, 10], wheelY: 4, wing: [0, 0, 7, 4],
      rows: [
        '..................................',
        '.KKKKKK......KKKKKKKK.............',
        '.KhhhhK....KKhhhhhhhhK............',
        '...KK....KKhgGGGGGGGGwgK..........',
        '..KKKKKKKhhhBgGGGGGGGGGwgKK.......',
        '.KhhhhhhhhhhhhBBBBBBBBBBBBhhhKKK..',
        '.KRBBBBBBBBBBBBBVVVVBBBBBBBBhhhhK.',
        '.KRBBBBBBBBBBBBBBVVVBBBBBBBBBBBBLK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbOK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'maklen95', name: 'MAKLEN F-UNO', year: 1995, era: 90, price: 28000, paint: '#4a4a5e', accent: '#ff7a1a', rims: 'chrome',
      stats: { top: 166, accel: 380, armor: 100, mass: 0.7, restComp: 2.3, damp: 0.45, hill: 0.58, launch: 1.34, air: 0.94 },
      desc: 'ЦЕНТРАЛЬНЕ КЕРМО, ЧИСТА НАУКА', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '............KKKK..................',
        '...........KVhhhhhKK..............',
        '.........KKhhgGGGGGgK.............',
        '.......KKhhhhgGGGGGGwgK...........',
        '..KKKKKhhhhhhhgGGGGGGGGwgKKKKK....',
        '.KhhhhhhhhhhhhBBBBBBBBBBBBhhhhhhK.',
        '.KRBBBBBBBBBBBBBBBVVVBBBBBBBBBBLK.',
        '.KRSSSSSSSSSSSSSSSSSSSSSSSSSSSSSOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'supra94', name: 'TOYOKA SUPRA-X', year: 1994, era: 90, price: 18000, paint: '#ff8a1a', accent: '#24202e', rims: 'chrome',
      stats: { top: 154, accel: 360, armor: 120, mass: 0.8, restComp: 2.5, damp: 0.4, hill: 0.6, launch: 1.42, air: 0.95 },
      desc: 'ДЕСЯТИСЕКУНДНА ЛЕГЕНДА', wheelX: [-10, 10], wheelY: 4, wing: [0, 0, 8, 4],
      rows: [
        '.KKKKKKK..........................',
        '.KhhhhhK....KKKKKKK...............',
        '..K...K...KKhhhhhhhKK.............',
        '..K...K..KhgGGGGGGGwgK............',
        '.KKKKKKKKhhhgGGGGGGGGGwgKKKKK.....',
        '.KhhhhhhhhhhhhBBBBBBBBBBBhhhhhhK..',
        '.KRRBBBBBBBBBBBBBBBBBBBBBBBBBBLK..',
        '.KRRBBBBBBBBBBBBBBBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbVK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'gtr99', name: 'NISAN GT-R34', year: 1999, era: 90, price: 21000, paint: '#2f7bff', accent: '#24202e', rims: 'black',
      stats: { top: 156, accel: 380, armor: 130, mass: 0.85, restComp: 2.5, damp: 0.4, hill: 0.7, launch: 1.34, air: 0.97 },
      desc: 'ГОДЗІЛА З ПОВНИМ ПРИВОДОМ', wheelX: [-10, 10], wheelY: 4, wing: [0, 0, 7, 4],
      rows: [
        '..........KKKKKKKKK...............',
        '.KKKKKK..KhhhhhhhhhK..............',
        '...KK...KgGGGGGwTgGGGGwK..........',
        '...KK..KgGGGGGGwTgGGGGGwK.........',
        '.KKKKKKhhhhhhhhhhhhhhhhhhKKKKKKKK.',
        '.KhhhhhBBBBBBBBBBBBBBBBBBhhhhhhhhK',
        '.KRRBBBBBBBBBBBBBBBBBBBBBBBBBBLLVK',
        '.KRRBBBBBBBBBBBBbBBBBBBBBBBBBBBBVK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbVK',
        '.KdddddddddddddddddddddddddddddVVK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'rx793', name: 'MAZRA RX-SEVEN', year: 1993, era: 90, price: 15000, paint: '#f5c131', accent: '#24202e', rims: 'white',
      stats: { top: 150, accel: 340, armor: 100, mass: 0.7, restComp: 2.3, damp: 0.44, hill: 0.6, launch: 1.36, air: 0.9 },
      desc: 'РОТОРНИЙ ВИСК ДО 9000', wheelX: [-10, 10], wheelY: 4, wing: [0, 0, 6, 4],
      rows: [
        '..................................',
        '.KKKKK......KKKKKK................',
        '.K...K....KKhhhhhhKK..............',
        '.K...K..KhgGGGGGGwgK..............',
        '.KKKKKKKhhhgGGGGGGGGwgKKKK........',
        '.KhhhhhhhhhhBBBBBBBBBBBBhhhhhKKK..',
        '.KRBBBBBBBBBBBBBBBBBBBBBBBBBBhhLK.',
        '.KRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'sti04', name: 'SUBARA WRX STI', year: 2004, era: 2000, price: 26000, paint: '#2a4fb8', accent: '#f5c131', rims: 'gold',
      stats: { top: 152, accel: 400, armor: 140, mass: 0.8, restComp: 2.8, damp: 0.36, hill: 0.78, launch: 1.36, air: 0.95 },
      desc: 'РАЛІЙНИЙ ПЛЕМІННИК', wheelX: [-10, 10], wheelY: 4, wing: [[0, 0, 8, 3], [0, 3, 7, 4]],
      rows: [
        '..........KKKKKKKKK...............',
        '.KKKKKKK.KhhhhhhhhhK..............',
        '.KhhhhhK.KgGGGGwTgGGGGwK..........',
        '...K.K.KgGGGGGwTgGGGGGwK..........',
        '.KKKKKKhhhhhhhhhhhhhhhhhKKVVKKKKK.',
        '.KhhhhhBBBBBBBBBBBBBBBBBhhhhhhhhK.',
        '.KRRBBBBBBBBBBBBBBBBBBBBBBBBBBBLK.',
        '.KBBBBBBBBBBBBBBbBBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbVK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'evo06', name: 'MITSU EVO-IX', year: 2006, era: 2000, price: 27000, paint: '#f2eefa', accent: '#d8203a', rims: 'black',
      stats: { top: 154, accel: 410, armor: 135, mass: 0.8, restComp: 2.8, damp: 0.36, hill: 0.76, launch: 1.36, air: 0.95 },
      desc: 'ЛАНСЕР, ЩО З\'ЇДАЄ ПОВОРОТИ', wheelX: [-10, 10], wheelY: 4, wing: [[0, 0, 8, 2], [0, 2, 7, 4]],
      rows: [
        '..KKKKKK..KKKKKKKKK...............',
        '..KhhhhK.KhhhhhhhhhK..............',
        '..K.KK..KgGGGGwTgGGGGGwK..........',
        '..K.KK.KgGGGGGwTgGGGGGGwK.........',
        '.KKKKKKhhhhhhhhhhhhhhhhhhKVKVKKKK.',
        '.KhhhhhBBBBBBBBBBBBBBBBBBhhhhhhhK.',
        '.KRRBBBBBBBBBBBBBBBBBBBBBBBBBBLLK.',
        '.KBBBBBBBBBBBBBBbBBBBBBBBBBBBBBBVK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbVK',
        '.KdddddddddddddddddddddddddddddVVK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'm3gtr05', name: 'BAVARIA M3 GTR', year: 2005, era: 2000, price: 36000, paint: '#b9bfcc', accent: '#2f7bff', rims: 'chrome',
      stats: { top: 164, accel: 390, armor: 130, mass: 0.8, restComp: 2.5, damp: 0.42, hill: 0.68, launch: 1.36, air: 0.94 },
      desc: 'НАЙРОЗШУКУВАНІШЕ АВТО МІСТА', wheelX: [-10, 10], wheelY: 4, wing: [0, 0, 7, 4],
      rows: [
        '..........KKKKKKKKK...............',
        '.KKKKKK..KhhhhhhhhhKK.............',
        '..KK....KhgGGGGGGGGGGwK...........',
        '..KK...KhhgGGGGwTgGGGGGGwK........',
        '.KKKKKKhhhhhhhhhhhhhhhhhhhKKKKKKK.',
        '.KhhhhhSSSSSSSSSSSSSSSSSSShhhhhhK.',
        '.KRRBsssssssssssssssssssssBBBBLLK.',
        '.KBBBBBBBBBBBBBBbBBBBBBBBBBBBBBBVK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbVK',
        '.KdddddddddddddddddddddddddddddVVK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK.',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.',
      ],
    },
    {
      id: 'mustar05', name: 'MUSTAR GT', year: 2005, era: 2000, price: 24000, paint: '#24202e', accent: '#f2eefa', rims: 'black',
      stats: { top: 158, accel: 350, armor: 155, mass: 1.0, restComp: 2.8, damp: 0.34, hill: 0.58, launch: 1.3, air: 1.0 },
      desc: 'РЕТРО-МЯЗИ, НОВЕ СЕРЦЕ', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '...........KKKKKKK................',
        '.........KKhSShhhK................',
        '.......KKgGGGGGGGgK...............',
        '.....KKhgGGGGGGGGGwgK.............',
        '.KKKKhhhhgGGGGGGGGGGGwgKKKKKKKK...',
        '.KhhhhBBBBBBBBBBBBBBBBBBhSShhSShK.',
        '.KRBBBBBBBBBBBBBBBBBBBBBBBBBBBBLK.',
        '.KRBBBBBBBBBBBBBVBBBBBBBBBBBBBBBVK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbCK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'carrera04', name: 'PORZA CARRERA-G', year: 2004, era: 2000, price: 52000, paint: '#9aa0b0', accent: '#24202e', rims: 'chrome',
      stats: { top: 172, accel: 430, armor: 110, mass: 0.7, restComp: 2.2, damp: 0.46, hill: 0.64, launch: 1.38, air: 0.92 },
      desc: 'V10 ПРОСТО З ЛЕ-МАНУ', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '..................................',
        '............KKKKKK................',
        '..........KKhhhhhhK...............',
        '........KKhhgGGGGGwgK.............',
        '..KKKKKKhhhhgGGGGGGGwgKKKKKK......',
        '.KKhhhhhhhhhhBBBBBBBBBBhhhhhhhKK..',
        '.KRBBBBBBBBBVVVVVBBBBBBBBBBBBBBLK.',
        '.KRBBBBBBBBBBVVVVBBBBBBBBBBBBBBBOK',
        '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
        '.KdddddddddddddddddddddddddddddddK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
    {
      id: 'veyra08', name: 'VEYRA 16.4', year: 2008, era: 2000, price: 95000, paint: '#2a4fb8', accent: '#24202e', rims: 'chrome',
      stats: { top: 184, accel: 480, armor: 150, mass: 0.9, restComp: 2.6, damp: 0.42, hill: 0.7, launch: 1.4, air: 0.92 },
      desc: 'ШІСТНАДЦЯТЬ ЦИЛІНДРІВ. КРАПКА.', wheelX: [-10, 10], wheelY: 4,
      rows: [
        '...........KKKKKKKK...............',
        '.........KSSSSSSSSSSK.............',
        '........KSSgGGGGGGwgSK............',
        '......KSSSgGGGGGGGGwgK............',
        '..KKKSSSSSSSgGGGGGGGGGwgKKKKK.....',
        '.KSSSSSSSSSSSBBBBBBBBBBBBhhhhhhK..',
        '.KRSSSSSSSSSBBBBBBBBBBBBBBBBBBLK..',
        '.KRSSSSSSSSBBBBVVVVBBBBBBBBBBBBCK.',
        '.KSSSSSSSSBBBBBVVVBBBBBBBBBBBBBCCK',
        '.KssssssssbbbbbbbbbbbbbbbbbbbbbbbK',
        '..KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK..',
        '...KKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
      ],
    },
  ];

  const PAINTS = [
    { id: 'ruby', name: 'РУБІН', c: '#d8203a' }, { id: 'flamingo', name: 'ФЛАМІНГО', c: '#ff3ea5' },
    { id: 'orange', name: 'ПОМАРАНЧ', c: '#ff8a1a' }, { id: 'gold', name: 'ЗОЛОТО', c: '#f5c131' },
    { id: 'lime', name: 'ЛАЙМ', c: '#7ae83a' }, { id: 'mint', name: 'МЯТА', c: '#29e0b0' },
    { id: 'teal', name: 'БІРЮЗА', c: '#29c7d8' }, { id: 'ocean', name: 'ОКЕАН', c: '#2f7bff' },
    { id: 'rally', name: 'РАЛІ', c: '#2a4fb8' }, { id: 'indigo', name: 'ІНДИГО', c: '#3b3fb8' },
    { id: 'violet', name: 'ФІАЛКА', c: '#8a3be8' }, { id: 'silver', name: 'СРІБЛО', c: '#b9bfcc' },
    { id: 'white', name: 'ПЕРЛИНА', c: '#f2eefa' }, { id: 'graphite', name: 'ГРАФІТ', c: '#4a4a5e' },
    { id: 'black', name: 'НІЧ', c: '#24202e' }, { id: 'sand', name: 'ПІСОК', c: '#d9c08a' },
  ];

  const PARTS = {
    vinyl: [
      { id: 'none', name: 'БЕЗ ВІНІЛУ', price: 0 }, { id: 'stripe', name: 'ГОНОЧНА СМУГА', price: 500 },
      { id: 'twin', name: 'ПОДВІЙНІ СМУГИ', price: 650 }, { id: 'flames', name: 'ПОЛУМЯ', price: 900 },
      { id: 'checker', name: 'ШАХІВНИЦЯ', price: 800 }, { id: 'bolt', name: 'БЛИСКАВКА', price: 750 },
      { id: 'sunset', name: 'ДВОКОЛІР', price: 700 }, { id: 'tribal', name: 'ТРАЙБЛ', price: 850 },
    ],
    spoiler: [
      { id: 'stock', name: 'ЗАВОДСЬКИЙ', price: 0 }, { id: 'none', name: 'БЕЗ СПОЙЛЕРА', price: 150 },
      { id: 'duck', name: 'КАЧИНИЙ ХВІСТ', price: 450 }, { id: 'gt', name: 'GT КРИЛО', price: 800 },
      { id: 'hoop', name: 'АРКА', price: 1000 }, { id: 'swan', name: 'ЛЕБЕДИНА ШИЯ', price: 1200 },
    ],
    bumper: [
      { id: 'stock', name: 'ЗАВОДСЬКИЙ', price: 0 }, { id: 'lip', name: 'ГУБА', price: 350 },
      { id: 'splitter', name: 'СПЛІТЕР', price: 650 }, { id: 'aggro', name: 'АГРЕСІЯ', price: 950 },
    ],
    skirt: [
      { id: 'stock', name: 'ЗАВОДСЬКІ', price: 0 }, { id: 'slim', name: 'ТОНКІ', price: 300 },
      { id: 'aero', name: 'АЕРО', price: 700 },
    ],
    rims: [
      { id: 'chrome', name: 'ХРОМ', price: 200, c: '#e6ecf5', d: '#8a93a8' }, { id: 'gold', name: 'ЗОЛОТО', price: 450, c: '#ffc31f', d: '#a86a10' },
      { id: 'black', name: 'ЧОРНИЙ МАТ', price: 300, c: '#4a4260', d: '#2a2238' }, { id: 'white', name: 'БІЛІ', price: 300, c: '#f2eefa', d: '#b9b6d6' },
      { id: 'pink', name: 'НЕОН РОЖЕВИЙ', price: 550, c: '#ff5cb8', d: '#a8206a' }, { id: 'cyan', name: 'НЕОН ЦІАН', price: 550, c: '#5cf0ff', d: '#1f8aa8' },
    ],
    glow: [
      { id: 'none', name: 'ВИМКНЕНО', price: 0 }, { id: 'pink', name: 'РОЖЕВА', price: 700, c: '#ff3ea5' },
      { id: 'cyan', name: 'ЦІАН', price: 700, c: '#29e0d0' }, { id: 'green', name: 'ЗЕЛЕНА', price: 700, c: '#6aff5a' },
      { id: 'violet', name: 'ФІОЛЕТОВА', price: 800, c: '#9d5cff' }, { id: 'gold', name: 'ЗОЛОТА', price: 900, c: '#ffc31f' },
      { id: 'red', name: 'ЧЕРВОНА', price: 800, c: '#ff2a3a' },
    ],
  };

  // performance upgrades: 4 levels (0 = stock)
  const LEVEL_NAMES = ['СТОК', 'СТРІТ', 'ПРО', 'УЛЬТИМЕЙТ'];
  const UPGRADES = [
    { id: 'engine', name: 'ДВИГУН', desc: 'МАКС. ШВИДКІСТЬ', icon: 'engine', cost: [0, 700, 1700, 3600] },
    { id: 'turbo', name: 'ТУРБО', desc: 'РОЗГІН', icon: 'turbo', cost: [0, 800, 1900, 3900] },
    { id: 'gearbox', name: 'КОРОБКА', desc: 'РОЗГІН І ШВИДКІСТЬ', icon: 'gear', cost: [0, 600, 1500, 3200] },
    { id: 'tires', name: 'ШИНИ', desc: 'ПІДЙОМИ І ВИЛІТ З ВІРАЖІВ', icon: 'tire', cost: [0, 500, 1300, 2800] },
    { id: 'suspension', name: 'ПІДВІСКА', desc: 'ДОВШІ СТРИБКИ', icon: 'spring', cost: [0, 550, 1400, 3000] },
    { id: 'chassis', name: 'КАРКАС', desc: 'МІЦНІСТЬ КУЗОВА', icon: 'shield', cost: [0, 500, 1200, 2700] },
  ];

  const ALL = STARTERS.concat(SHOP);
  const byId = {};
  ALL.forEach((c) => (byId[c.id] = c));

  window.Catalog = { STARTERS, SHOP, ALL, byId, PAINTS, PARTS, UPGRADES, LEVEL_NAMES };
})();
